application: bcherry
version: 1
runtime: python
api_version: 1

inbound_services:
- xmpp_message

handlers:
# Static CSS/JS/IMG/JSON including specified sub-apps
- url: /(blaster/|playground/|arguments/|spptoolbar/|js-better-faster/|talks/|)static/(lib/|)(js|img|css|data)/(.*)
  static_files: \1static/\2\3/\4
  upload: (blaster/|playground/|arguments/|spptoolbar/|js-better-faster/|talks/|)static/.*

# Blaster Project
- url: /blaster
  script: /blaster/main.py

# Playground
- url: /playground/?.*
  script: /playground/main.py

# Bad Globals Demo Page
- url: /badglobals
  script: /badglobals/main.py

# Arguments Demo Page
- url: /arguments
  script: /arguments/main.py

# SPP Toolbar Demo Page
- url: /spptoolbar
  script: /spptoolbar/main.py

# JavaScript: Better, Faster Presentation (original Slide version)
- url: /js-better-faster/?.*
  script: /js-better-faster/main.py

- url: /talks/(.*)/(.*).css
  static_files: talks/\1/\2.css
  upload: talks/(.*)/(.*).css

# Talks and Presentations
- url: /talks/?.*
  script: /talks/main.py

# XMPP
- url: /_ah/xmpp/message/chat/
  script: xmpp.py

# Main Page
- url: .*
  script: main.py

