application: bcherry
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.+?/|)?(scripts|images|styles)/(.*)
  static_files: \1content/\2/\3
  upload: /content/(scripts|images|styles)/.*?\.(js|css|gif|png|jpg)

- url: .*
  script: main.py
