application: bcherry
version: 1
runtime: python
api_version: 1

handlers:
# Static CSS/JS/IMG, including specified sub-apps
- url: /(blaster/|)static/(lib/|)(js|img|css)/(.*)
  static_files: \1static/\2\3/\4
  upload: (blaster/|)static/.*
    
# Blaster Project
- url: /blaster
  script: /blaster/main.py

# Main Page
- url: .*
  script: main.py
