application: bcherry
version: 1
runtime: python
api_version: 1

handlers:
# Static CSS/JS/IMG, including sub-apps
- url: /(.+?/|)?(js|images|css)/(.*)
  static_files: \1static/\2/\3
  upload: (.*?/)?static/(js|images|css)/.*?\.(js|css|gif|png|jpg)

# Pets
- url: /pets
  script: /pets/main.py

# AGD Project
- url: /agd
  script: /agd/main.py

# Blaster Project
- url: /blaster
  script: /blaster/main.py


# Main Page
- url: .*
  script: main.py
