application: bcherry
version: 1
runtime: python
api_version: 1

handlers:
- url: /styles
  static_dir: content/styles

- url: /scripts
  static_dir: content/scripts
 
- url: /images
  static_dir: content/images

- url: .*
  script: main.py
