# $Id: GNUmakefile,v 351.7 2005-03-03 14:56:02-08 - - $
# Ben Cherry - CMPS012B - Wesley Mackey - Winter 05 - Asg 5
CC      = /opt/SUNWspro/bin/cc
CCOPT   = -D__EXTENSIONS__ -g -xO0 -Xc -xarch=v8
CCDEP   = -xM1
LINT    = /opt/SUNWspro/bin/lint
LINTOPT = -D__EXTENSIONS__ -Xa -fd -m -u -x -errchk=%all

CHEADER  =            buffer.h auxlib.h bstree.h
CSOURCE  = wordfreq.c buffer.c auxlib.c bstree.c
OBJECTS  = ${patsubst %.c, %.o, ${CSOURCE}}
EXECBIN  = wordfreq
MKFILE   = GNUmakefile
SOURCES  = ${CHEADER} ${CSOURCE} ${MKFILE} README
LISTING  = asg5c-wordfreq_listing.ps
CID	 = /afs/cats.ucsc.edu/courses/cmps012b-wm/sparcbin/cid

all : ${EXECBIN}

${EXECBIN} : ${OBJECTS}
	cc ${CCOPT} -o $@ ${OBJECTS}

%.o : %.c
	cc ${CCOPT} -c $<

lint : ${CSOURCE}
	lint ${LINTOPT} ${CSOURCE}

ci : ${SOURCES}
	${CID} + ${SOURCES}

lis : ../${LISTING}
	ghostview -magstep 1 ../${LISTING} &

../${LISTING} : ${SOURCES}
	- enscript -G -p ../${LISTING} ${SOURCES}
	cd ..; ps2pdf ${LISTING}

clean :
	- rm ${OBJECTS} ${MKFILE}.old core

spotless : clean
	- rm ${EXECBIN}

deps : ${CSOURCE} ${CHEADER}
	cid + ${MKFILE}
	perl -ni -e 'print unless m/^\S+\.o: \S+\.[hc]$$/' ${MKFILE}
	cc -xM1 ${CSOURCE} | sort | uniq | tee -a ${MKFILE}
	cid + ${MKFILE}

again :
	gmake spotless
	gmake deps
	gmake ci
	gmake all
	gmake lis

test : ${EXECBIN}
	- ${EXECBIN} test*.data nosuchfile >test.out1 2>test.err1
	- bcheck -all ${EXECBIN} test*.data >test.out2 2>test.err2

#================================================================
# DO NOT PUT ANY LINES IN THIS MAKEFILE THAT MATCH THE NAMES
# OF ANY OF THE OBJECT FILES.  `gmake deps' WILL DELETE AND
# REPLACE THEM BY THE NEW DEPENDENCIES AT THE END OF THE FILE.
#================================================================
auxlib.o: auxlib.c
auxlib.o: auxlib.h
bstree.o: bstree.c
bstree.o: bstree.h
buffer.o: auxlib.h
buffer.o: buffer.c
buffer.o: buffer.h
wordfreq.o: auxlib.h
wordfreq.o: buffer.h
wordfreq.o: wordfreq.c
